AttachSpec("spec");
load "./Tests/t-Create.m";
print("PASS");
load "./Tests/t-RHS.m";
print("PASS");
load "./Tests/t-ReduciblePlaces.m";
print("PASS");
load "./Tests/t-Invariants.m";
print("PASS");
load "./Tests/t-ReducibleFiber.m";
print("PASS");
exit;
